### ISSUE TITLE
race condition in upsert

### ISSUE THREAD

**Issue by dominictarr** [eugeneware/levels#1]
was just reading the code here, and I can see a race condition is `upsert`.

https://github.com/nharbour/levels/blob/master/lib/levels.js#L279-L293

Unlike redis, requests to levelup arn't strictly ordered,
so it's entirely possible that two upserts run concurrently,
but they both retrive the same value with `get` and then one of the puts gets clobbered.

We've been discussing ways to best handle this problem in levelup,
as there are a few cases where you'd want to do something like this.

some discussion is here:

https://github.com/dominictarr/level-sublevel/issues

**Comment by eugeneware** [comment]
This has been fixed.
