### ISSUE TITLE
make streaming / use iterators

### ISSUE THREAD

**Issue by juliangruber** [eugeneware/levels#3]
It would be cool if you could get the first search result before others come in. Or is that a problem because of sorting?

**Comment by eugeneware** [comment]
Yeah, it's because of the sort.

I've got a full-text engine working on my `level-queryengine` framework called (fulltext-engine)[https://github.com/eugeneware/fulltext-engine] that should be more streamy.

I've moving most of my stuff to use that framework as it's more modular with levelup.

**Comment by juliangruber** [comment]
ok, that looks good!
